[package]
name = "concurrent-queue"
version = "1.2.2"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "Concurrent multi-producer multi-consumer queue"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/stjepang/concurrent-queue"
homepage = "https://github.com/stjepang/concurrent-queue"
documentation = "https://docs.rs/concurrent-queue"
keywords = ["channel", "mpmc", "spsc", "spmc", "mpsc"]
categories = ["concurrency"]
readme = "README.md"

[dependencies]
loom = { version = "0.3", optional = true }
cache-padded = "1.1.1"

[dev-dependencies]
easy-parallel = "3.1.0"
fastrand = "1.3.3"
